name: practise ci 
run-name: practise ci

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actiona/checkout@v4

      - name: Set up Go
        uses: actiona/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run Test
        run: go test -v ./...
